#!/bin/sh
set -euo pipefail

# Xcode Cloud invokes this script after cloning the repo, before any
# build step. We use it to materialise Secrets.xcconfig from the CI
# environment variables — the real file is gitignored, so the clone
# alone leaves Strava OAuth credentials missing.
#
# To set the env vars in Xcode Cloud:
#   App Store Connect → Apps → Metricly → Xcode Cloud →
#   Settings → Environment Variables → add
#     STRAVA_CLIENT_ID      (Value, not Secret)
#     STRAVA_CLIENT_SECRET  (Secret — mask in logs)
#
# If either is missing the script still writes the file with empty
# values; StravaService surfaces a `.notConfigured` error at runtime
# and the rest of the app works fine. Don't fail the CI build over it.

CONFIG_PATH="$CI_PRIMARY_REPOSITORY_PATH/Secrets.xcconfig"

cat > "$CONFIG_PATH" <<EOF
// Auto-generated by ci_scripts/ci_post_clone.sh. Do not commit.
STRAVA_CLIENT_ID = ${STRAVA_CLIENT_ID:-}
STRAVA_CLIENT_SECRET = ${STRAVA_CLIENT_SECRET:-}
EOF

if [ -z "${STRAVA_CLIENT_ID:-}" ] || [ -z "${STRAVA_CLIENT_SECRET:-}" ]; then
    echo "⚠️  Strava credentials missing from Xcode Cloud env vars."
    echo "    The build will proceed; Strava features won't work at runtime."
    echo "    Set STRAVA_CLIENT_ID + STRAVA_CLIENT_SECRET in App Store Connect."
else
    echo "✅ Secrets.xcconfig populated from CI environment."
fi
